name: tansik
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  toastification: ^3.0.3
  flex_color_scheme: ^8.3.1
  flutter_native_splash: ^2.4.7
  http: ^1.6.0
  flutter_scrapper: ^1.1.0
  flutter_offline: ^6.0.0
  simple_gradient_text: ^1.4.0
  lottie: ^3.3.3
  shared_preferences: ^2.5.5

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/lottie/


  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai-Light.ttf
        - asset: assets/fonts/Almarai-Regular.ttf
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Bold.ttf
        - asset: assets/fonts/NotoNaskhArabic-Medium.ttf
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf
        - asset: assets/fonts/NotoNaskhArabic-SemiBold.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf
        - asset: assets/fonts/Rubik-BlackItalic.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik-BoldItalic.ttf
        - asset: assets/fonts/Rubik-ExtraBold.ttf
        - asset: assets/fonts/Rubik-ExtraBoldItalic.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
        - asset: assets/fonts/Rubik-Light.ttf
        - asset: assets/fonts/Rubik-LightItalic.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-MediumItalic.ttf
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-SemiBold.ttf
        - asset: assets/fonts/Rubik-SemiBoldItalic.ttf